#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

log_msg() {
    local level="$1"     # Log level: info, warn, err, debug
    local msg="$2"       # Message to log
    echo "$msg"          # Still shows on console
    logger -t "vwifi-client" -p daemon.$level "$msg"  # Sends to syslog
}

start_service() {
	local enabled server_ip number mac_prefix
	
	config_load vwifi
	config_get enabled config 'enabled' '0'
	config_get server_ip config 'server_ip' '172.16.0.1'
	config_get number config 'number' '1'
	config_get mac_prefix config 'mac_prefix' '74:f8:f6:66'
	
	[ "$enabled" = "1" ] || {
		echo "vwifi-client is disabled in /etc/config/vwifi"
		log_msg "warn" "vwifi-client is disabled "

		return 1
	}
	
	[ -n "$server_ip" ] || {
		echo "Error: server_ip not configured in /etc/config/vwifi"
		log_msg "info" "server_ip not configured"

		return 1
	}
	
	echo "Starting vwifi-client connecting to $server_ip with $number radio(s)"
	log_msg "info" "Starting vwifi-client connecting to $server_ip with $number radio(s)"
	
	procd_open_instance
	procd_set_param command /usr/sbin/vwifi-client
	procd_append_param command "$server_ip"
	procd_append_param command "--number"
	procd_append_param command "$number"
	
	# Add MAC prefix if configured
	[ -n "$mac_prefix" ] && {
		procd_append_param command "--mac"
		procd_append_param command "$mac_prefix"
	}
	
	# Process configurations
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/vwifi-client.pid
	
	procd_close_instance
}

stop_service() {
	echo "Stopping vwifi-client"
	# Clean up virtual radios if they exist
	for iface in $(iw dev | awk '/Interface/ {print $2}' | grep -E '^wlan[0-9]+$'); do
		echo "Removing virtual interface $iface"
		iw dev "$iface" del 2>/dev/null || true
	done
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "vwifi"
}